# Generated by Django 4.1.2 on 2022-10-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artistes_lyrics_songs_remove_lyric_song_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artistes',
            new_name='Artiste',
        ),
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
